In [1]:
import numpy as np
import torch

In [2]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

In [3]:
# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [4]:
# Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [19]:
# Weights and biases
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[ 0.2314, -1.5057,  0.3818],
        [ 1.9163, -0.1713, -0.0775]], requires_grad=True)
tensor([ 1.0342, -2.3139], requires_grad=True)


In [20]:
def model(x):
    return x @ w.t() + b

In [21]:
# Generate predictions
preds = model(inputs)
print(preds)

tensor([[ -66.5365,  122.7687],
        [ -85.9727,  152.0383],
        [-158.4498,  136.9576],
        [ -25.9808,  182.9180],
        [-100.8179,  108.0441]], grad_fn=<AddBackward0>)


In [22]:
# MSE loss
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

In [23]:
# Compute loss
loss = mse(preds, targets)
print(loss)

tensor(19053.4551, grad_fn=<DivBackward0>)


In [24]:
# Compute gradients
loss.backward()

In [25]:
# Gradients for weights
print(w)
print(w.grad)  # derivative
print(b.grad)

tensor([[ 0.2314, -1.5057,  0.3818],
        [ 1.9163, -0.1713, -0.0775]], requires_grad=True)
tensor([[-13447.0586, -16342.3018,  -9617.9902],
        [  4593.7178,   2755.9797,   2079.4194]])
tensor([-163.7515,   48.5453])


In [26]:
print(b)
print(b.grad) # 

tensor([ 1.0342, -2.3139], requires_grad=True)
tensor([-163.7515,   48.5453])


In [27]:
# adjust weight  & reset perdiction
with torch.no_grad():
  w-=w.grad  * 1e-5  # reduce the weight
  b-=b.grad  * 1e-5 
  w.grad.zero_()
  b.grad.zero_() 


In [28]:


print(w)
print(b)

tensor([[ 0.3659, -1.3422,  0.4780],
        [ 1.8704, -0.1989, -0.0983]], requires_grad=True)
tensor([ 1.0358, -2.3143], requires_grad=True)


In [29]:
# calculate loss

# loss we reduce after changing the bias weight
preds=model(inputs)
loss=mse(preds,targets)
print(loss)

tensor(13829.0625, grad_fn=<DivBackward0>)


In [30]:
# train 1000 epochs   # this will increase the accuracy
for i in range(100):
  preds=model(inputs)
  loss=mse(preds,targets)
  loss.backward()
  with  torch.no_grad():
    w -=w.grad * 1e-5
    b -=b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [31]:
preds=model(inputs)
loss=mse(preds,targets)
print(loss)

tensor(906.9205, grad_fn=<DivBackward0>)


In [32]:
# Predictions
preds

tensor([[ 65.4897,  80.5002],
        [ 91.3295, 102.0123],
        [ 84.5657, 113.5149],
        [ 68.8081,  97.9462],
        [ 90.1441,  85.4579]], grad_fn=<AddBackward0>)

In [33]:
# target
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [34]:
# train 1000 epochs   # this will increase the accuracy
for i in range(55):
  preds=model(inputs)
  loss=mse(preds,targets)
  loss.backward()
  with  torch.no_grad():
    w -=w.grad * 1e-5
    b -=b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [35]:
preds=model(inputs)
loss=mse(preds,targets)
print(loss)

tensor(471.1003, grad_fn=<DivBackward0>)


In [36]:
# Predictions
preds

tensor([[ 63.0072,  77.5686],
        [ 89.2637, 100.1005],
        [ 93.2550, 122.5759],
        [ 54.3422,  80.9164],
        [ 94.9916,  92.0696]], grad_fn=<AddBackward0>)

In [37]:
# target
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [38]:
import torch.nn  as nn 

In [39]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [74, 66, 43], 
                   [91, 87, 65], 
                   [88, 134, 59], 
                   [101, 44, 37], 
                   [68, 96, 71], 
                   [73, 66, 44], 
                   [92, 87, 64], 
                   [87, 135, 57], 
                   [103, 43, 36], 
                   [68, 97, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], 
                   dtype='float32')

inputs = torch.from_numpy(inputs)  # CONVT TO TENSOR
targets = torch.from_numpy(targets)

In [40]:
inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 74.,  66.,  43.],
        [ 91.,  87.,  65.],
        [ 88., 134.,  59.],
        [101.,  44.,  37.],
        [ 68.,  96.,  71.],
        [ 73.,  66.,  44.],
        [ 92.,  87.,  64.],
        [ 87., 135.,  57.],
        [103.,  43.,  36.],
        [ 68.,  97.,  70.]])

In [42]:
from  torch.utils.data import TensorDataset

In [44]:
train_ds= TensorDataset(inputs,targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [45]:
from torch.utils.data  import DataLoader


In [46]:
batch_size = 5
train_dl = DataLoader(train_ds,batch_size,shuffle=True)

In [47]:
for xb,yb in train_dl:
  print(xb)
  print(yb)
  break

tensor([[ 91.,  87.,  65.],
        [101.,  44.,  37.],
        [ 69.,  96.,  70.],
        [ 74.,  66.,  43.],
        [ 73.,  66.,  44.]])
tensor([[ 80., 102.],
        [ 21.,  38.],
        [103., 119.],
        [ 57.,  69.],
        [ 57.,  69.]])


In [48]:
# define model
model=nn.Linear(3,2) # 3 input 2 output(target)
print(model.weight)
model.bias

Parameter containing:
tensor([[-0.1364,  0.4244, -0.0957],
        [ 0.2113,  0.5294, -0.3695]], requires_grad=True)


Parameter containing:
tensor([-0.0945, -0.4044], requires_grad=True)

In [49]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.1364,  0.4244, -0.0957],
         [ 0.2113,  0.5294, -0.3695]], requires_grad=True),
 Parameter containing:
 tensor([-0.0945, -0.4044], requires_grad=True)]

In [50]:
# generate prediction
preds=model(inputs)
preds

tensor([[14.2685, 34.6065],
        [18.7164, 41.7690],
        [39.3587, 67.4948],
        [ 0.7010, 30.2458],
        [24.5385, 39.1380],
        [13.7077, 34.2884],
        [18.1963, 40.8700],
        [39.1266, 67.3366],
        [ 1.2618, 30.5639],
        [24.5792, 38.5572],
        [13.7484, 33.7075],
        [18.1555, 41.4509],
        [39.8787, 68.3937],
        [ 0.6603, 30.8266],
        [25.0993, 39.4561]], grad_fn=<AddmmBackward0>)

In [51]:
import  torch.nn.functional as F

In [53]:
# define loss fuct
loss_fn=F.mse_loss

In [54]:
# ?F.mse_loss  # help

In [55]:
loss=loss_fn(model(inputs),targets)
loss

tensor(3400.1550, grad_fn=<MseLossBackward0>)

In [56]:
# define optimizer
opt=torch.optim.SGD(model.parameters(),lr=1e-5) # short cut for gradient descent reducing weights

In [64]:
# to train model
def fit(num_epochs,model,loss_fn,opt,train_dl):
  # repeat for epochs
  for epoch in range(num_epochs):
    # train batch of data 
    for xb,yb in train_dl:
      # do prediction
      pred = model(xb)
      # calculate loss
      loss=loss_fn(pred,yb)
      # compute gradient 
      loss.backward()
      # update parameters
      opt.step() #for gradient descent reducing weights
      # 5. Reset the gradients to zero
      opt.zero_grad()
    if (epoch+1) % 10 ==0:
      print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1,num_epochs,loss.item()))

In [65]:
fit(100,model,loss_fn,opt,train_dl)

Epoch [10/100], Loss: 107.8586
Epoch [20/100], Loss: 180.9994
Epoch [30/100], Loss: 207.3060
Epoch [40/100], Loss: 76.1392
Epoch [50/100], Loss: 142.4207
Epoch [60/100], Loss: 52.0400
Epoch [70/100], Loss: 67.6488
Epoch [80/100], Loss: 71.4510
Epoch [90/100], Loss: 28.9237
Epoch [100/100], Loss: 28.7268


In [66]:
# generate prediction
preds=model(inputs)
preds

tensor([[ 57.9838,  71.8128],
        [ 79.4082,  95.3911],
        [123.0184, 142.8239],
        [ 26.1673,  45.2930],
        [ 94.1177, 105.0237],
        [ 56.7765,  70.7406],
        [ 78.7153,  94.4547],
        [123.0418, 142.9000],
        [ 27.3746,  46.3652],
        [ 94.6321, 105.1596],
        [ 57.2910,  70.8765],
        [ 78.2009,  94.3188],
        [123.7113, 143.7602],
        [ 25.6528,  45.1571],
        [ 95.3250, 106.0959]], grad_fn=<AddmmBackward0>)

In [67]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])